// routes/paymentSubmissionRoutes.js
import express from "express";
import multer from "multer";
import path from "path";
import { fileURLToPath } from "url";
import PaymentSubmission from "../models/PaymentSubmission.js";
import Payment from "../models/Payment.js";
import Transaction from "../models/Transaction.js";
import Student from "../models/Student.js";


// ✅ AUTOMATIC RECEIPT GENERATION FUNCTIONS - Add to paymentSubmissionRoutes.js
import Receipt from "../models/Receipt.js";

// Function to automatically generate receipt when payment is approved
const generateAutomaticReceipt = async (payment, actionType = 'approval') => {
  try {
    console.log(`🔄 Generating automatic receipt for ${actionType}:`, payment._id);
    
    // Only generate receipts for payments with actual paid amount
    if (payment.amountPaid <= 0) {
      console.log('⏭️ No amount paid, skipping automatic receipt generation');
      return null;
    }

    // Check if receipt already exists for this payment
    const existingReceipt = await Receipt.findOne({ paymentId: payment._id });
    
    if (existingReceipt) {
      console.log('📝 Updating existing receipt:', existingReceipt.receiptNumber);
      
      // Update existing receipt
      existingReceipt.amount = payment.amountPaid;
      existingReceipt.total = payment.amountPaid;
      existingReceipt.subtotal = payment.amountPaid;
      existingReceipt.items = [{
        description: payment.description,
        amount: payment.amountPaid,
        type: payment.type || 'tuition'
      }];
      existingReceipt.date = new Date();
      existingReceipt.status = 'completed';
      
      await existingReceipt.save();
      return existingReceipt;
    }

    // Generate new receipt
    const student = await Student.findOne({ studentId: payment.studentId });
    if (!student) {
      throw new Error(`Student not found: ${payment.studentId}`);
    }

    // Calculate balances
    const studentPayments = await Payment.find({ studentId: payment.studentId });
    const totalDue = studentPayments.reduce((sum, p) => sum + (p.amount || 0), 0);
    const totalPaid = studentPayments.reduce((sum, p) => sum + (p.amountPaid || 0), 0);
    const balanceRemaining = Math.max(0, totalDue - totalPaid);

    // Generate receipt number
    const receiptCount = await Receipt.countDocuments();
    const receiptNumber = `RCP-${String(receiptCount + 1).padStart(6, '0')}`;

    const receipt = new Receipt({
      receiptNumber,
      studentId: payment.studentId,
      studentName: student.fullName,
      studentEmail: student.email,
      studentCourse: student.course,
      paymentId: payment._id,
      amount: payment.amountPaid,
      description: payment.description,
      paymentMethod: 'approved_payment',
      status: 'completed',
      date: new Date(),
      items: [{
        description: payment.description,
        amount: payment.amountPaid,
        type: payment.type || 'tuition'
      }],
      subtotal: payment.amountPaid,
      tax: 0,
      total: payment.amountPaid,
      balanceInfo: {
        totalDue: totalDue,
        totalPaid: totalPaid,
        balanceRemaining: balanceRemaining
      },
      autoGenerated: true,
      generatedAt: new Date()
    });

    await receipt.save();
    
    // Update payment with receipt tracking
    await Payment.findByIdAndUpdate(payment._id, {
      receiptGenerated: true,
      receiptId: receipt._id,
      lastReceiptUpdate: new Date()
    });

    console.log('✅ Automatic receipt generated:', receipt.receiptNumber);
    return receipt;

  } catch (error) {
    console.error('❌ Error in automatic receipt generation:', error);
    throw error;
  }
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = express.Router();

// Configure multer for file uploads
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, path.join(__dirname, "../uploads/payments"));
  },
  filename: function (req, file, cb) {
    cb(null, Date.now() + '-' + Math.round(Math.random() * 1E9) + path.extname(file.originalname));
  }
});

const upload = multer({
  storage: storage,
  limits: {
    fileSize: 5 * 1024 * 1024 // 5MB limit
  },
  fileFilter: function (req, file, cb) {
    const filetypes = /jpeg|jpg|png|pdf/;
    const extname = filetypes.test(path.extname(file.originalname).toLowerCase());
    const mimetype = filetypes.test(file.mimetype);
    
    if (mimetype && extname) {
      return cb(null, true);
    } else {
      cb(new Error('Only image files (JPEG, PNG, JPG) and PDFs are allowed'));
    }
  }
});

// Submit payment for admin review
router.post('/submit-payment', upload.single('receipt'), async (req, res) => {
  try {
    console.log('Payment submission received:', req.body);
    console.log('File:', req.file);

    const {
      paymentId,
      studentId,
      amount,
      paymentMethod,
      transactionId,
      notes
    } = req.body;

    if (!studentId || !amount || !paymentId) {
      return res.status(400).json({
        success: false,
        message: 'Student ID, amount, and payment ID are required'
      });
    }

    // Verify the payment exists
    const payment = await Payment.findById(paymentId);
    if (!payment) {
      return res.status(404).json({
        success: false,
        message: 'Payment not found'
      });
    }

    // Verify payment belongs to this student
    if (payment.studentId !== studentId) {
      return res.status(403).json({
        success: false,
        message: 'This payment does not belong to this student'
      });
    }

    // Get student info
    const student = await Student.findOne({ studentId: studentId });
    const studentName = student ? student.fullName : `Student ${studentId}`;

    // Create submission object
    const submission = new PaymentSubmission({
      submissionId: `sub_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      originalPaymentId: paymentId,
      studentId: studentId,
      studentName: studentName,
      amount: parseFloat(amount),
      paymentMethod: paymentMethod || 'bank_transfer',
      transactionId: transactionId || `txn_${Date.now()}`,
      notes: notes || '',
      receiptFile: req.file ? `/uploads/payments/${req.file.filename}` : null,
      status: 'pending',
      paymentDescription: payment.description
    });

    // Save to database
    await submission.save();
    console.log('Stored submission in database:', submission);

    res.status(201).json({
      success: true,
      message: 'Payment submitted for review',
      submissionId: submission.submissionId
    });

  } catch (error) {
    console.error('Error submitting payment:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to submit payment: ' + error.message
    });
  }
});

// Get pending submissions for admin
router.get('/admin/pending-submissions', async (req, res) => {
  try {
    const pending = await PaymentSubmission.find({ status: 'pending' }).sort({ submittedAt: -1 });
    console.log('Returning pending submissions:', pending.length);
    
    res.json({
      success: true,
      submissions: pending
    });
  } catch (error) {
    console.error('Error fetching pending submissions:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch pending submissions'
    });
  }
});

// Get all submissions for admin
router.get('/admin/all-submissions', async (req, res) => {
  try {
    const allSubmissions = await PaymentSubmission.find().sort({ submittedAt: -1 });
    console.log('Returning all submissions:', allSubmissions.length);
    res.json({
      success: true,
      submissions: allSubmissions
    });
  } catch (error) {
    console.error('Error fetching all submissions:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch submissions'
    });
  }
});

// // Update payment status and process the payment
// router.put('/admin/update-status/:submissionId', async (req, res) => {
//   try {
//     const { submissionId } = req.params;
//     const { status, adminNotes } = req.body;

//     console.log('Updating submission:', submissionId, 'to:', status);

//     const submission = await PaymentSubmission.findOne({ submissionId: submissionId });
    
//     if (!submission) {
//       return res.status(404).json({
//         success: false,
//         message: 'Submission not found'
//       });
//     }

//     // Prevent double processing
//     if (submission.status !== 'pending') {
//       return res.status(400).json({
//         success: false,
//         message: `This submission has already been ${submission.status}`
//       });
//     }

//     // Update submission status
//     submission.status = status;
//     submission.adminNotes = adminNotes;
//     submission.reviewedAt = new Date();
//     await submission.save();

//     // If approved, update the original payment and create transaction
//     if (status === 'approved') {
//       await processApprovedPayment(submission);
//     }

//     res.json({
//       success: true,
//       message: `Payment ${status} successfully`
//     });

//   } catch (error) {
//     console.error('Error updating payment status:', error);
//     res.status(500).json({
//       success: false,
//       message: 'Failed to update payment status: ' + error.message
//     });
//   }
// });

// ✅ Update payment submission status - IMPROVED VERSION
// ✅ Update payment submission status - FIXED for proper payment updates
router.put('/admin/update-status/:submissionId', async (req, res) => {
  try {
    const { submissionId } = req.params;
    const { status, approvedAmount, notes } = req.body;

    console.log('Updating payment submission:', { submissionId, status, approvedAmount });

    // Find the submission by submissionId
    const submission = await PaymentSubmission.findOne({ submissionId: submissionId });
    if (!submission) {
      return res.status(404).json({
        success: false,
        message: 'Payment submission not found'
      });
    }

    // Prevent double processing
    if (submission.status !== 'pending') {
      return res.status(200).json({
        success: true,
        message: `Submission was already ${submission.status}`,
        submission: submission,
        alreadyProcessed: true
      });
    }

    // Update submission status
    submission.status = status;
    submission.reviewedAt = new Date();
    submission.reviewedBy = 'admin';
    submission.adminNotes = notes || submission.adminNotes;

    if (status === 'approved' && approvedAmount) {
      submission.approvedAmount = parseFloat(approvedAmount);
    }

    await submission.save();
    console.log('✅ Submission status updated to:', status);

    // ✅ If approved, update the original payment and generate receipt
    if (status === 'approved') {
      try {
        // Get student details
        const student = await Student.findOne({ studentId: submission.studentId });
        if (!student) {
          throw new Error(`Student not found: ${submission.studentId}`);
        }

        const paymentAmount = submission.approvedAmount || submission.amount;

        // ✅ Update the original payment (add to amountPaid)
        const originalPayment = await Payment.findById(submission.originalPaymentId);
        if (originalPayment) {
          console.log('✅ Updating original payment:', originalPayment._id);
          
          // Update the original payment - ADD to amountPaid
          const currentAmountPaid = originalPayment.amountPaid || 0;
          originalPayment.amountPaid = currentAmountPaid + paymentAmount;
          
          // Update status based on payment progress
          if (originalPayment.amountPaid >= originalPayment.amount) {
            originalPayment.status = 'completed';
          } else if (originalPayment.amountPaid > 0) {
            originalPayment.status = 'partial';
          } else {
            originalPayment.status = 'pending';
          }
          
          originalPayment.updatedAt = new Date();
          await originalPayment.save();

          console.log('✅ Payment updated - Amount paid:', originalPayment.amountPaid, 'Status:', originalPayment.status);

          // ✅ Generate automatic receipt
          try {
            const receipt = await generateAutomaticReceipt(originalPayment, 'submission_approval');
            console.log('✅ Automatic receipt generated:', receipt.receiptNumber);
          } catch (receiptError) {
            console.error('❌ Automatic receipt generation failed:', receiptError);
          }

          // Create transaction record for the payment
          const transaction = new Transaction({
            transactionId: `TXN${Date.now()}`,
            studentId: submission.studentId,
            studentName: student.fullName,
            description: `Payment approved: ${submission.paymentDescription}`,
            amount: paymentAmount,
            type: 'payment',
            status: 'completed',
            date: new Date(),
            paymentId: originalPayment._id,
            paymentMethod: submission.paymentMethod || 'bank_transfer',
            balanceBefore: student.accountBalance || 0,
            balanceAfter: (student.accountBalance || 0) - paymentAmount
          });

          await transaction.save();

          // Update student balance (reduce by paid amount)
          student.accountBalance = Math.max(0, (student.accountBalance || 0) - paymentAmount);
          student.lastUpdated = new Date();
          await student.save();

          console.log('✅ Student balance updated:', student.accountBalance);

        } else {
          console.log('⚠️ Original payment not found, creating new payment record');
          
          // Create new payment record if original not found
          const newPayment = new Payment({
            studentId: submission.studentId,
            studentName: student.fullName,
            studentEmail: student.email,
            studentCourse: student.course,
            amount: paymentAmount, // Total amount equals paid amount
            amountPaid: paymentAmount, // Full amount paid
            description: submission.paymentDescription || 'Approved Payment Submission',
            dueDate: new Date(),
            type: 'tuition',
            status: 'completed'
          });

          await newPayment.save();

          // ✅ Generate automatic receipt
          try {
            const receipt = await generateAutomaticReceipt(newPayment, 'submission_approval');
            console.log('✅ Automatic receipt generated for new payment:', receipt.receiptNumber);
          } catch (receiptError) {
            console.error('❌ Automatic receipt generation failed:', receiptError);
          }
        }

        console.log('✅ Payment processed successfully for approved submission');

      } catch (paymentError) {
        console.error('❌ Error processing payment:', paymentError);
      }
    }

    res.json({
      success: true,
      message: `Payment submission ${status} successfully`,
      submission,
      paymentProcessed: status === 'approved',
      receiptGenerated: status === 'approved'
    });

  } catch (error) {
    console.error('Error updating payment submission:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update payment submission',
      error: error.message
    });
  }
});

// Helper function to process approved payments
async function processApprovedPayment(submission) {
  try {
    console.log('Processing approved payment for submission:', submission.submissionId);

    // Find the original payment
    const originalPayment = await Payment.findById(submission.originalPaymentId);

    if (!originalPayment) {
      console.error('Original payment not found:', submission.originalPaymentId);
      throw new Error('Original payment not found');
    }

    console.log('Original payment found:', {
      id: originalPayment._id,
      studentId: originalPayment.studentId,
      amount: originalPayment.amount,
      amountPaid: originalPayment.amountPaid
    });

    // Calculate new amount paid
    const currentAmountPaid = originalPayment.amountPaid || 0;
    const newAmountPaid = currentAmountPaid + submission.amount;
    
    // Update payment record
    originalPayment.amountPaid = newAmountPaid;
    
    // Update status based on payment progress
    if (newAmountPaid >= originalPayment.amount) {
      originalPayment.status = 'completed';
    } else if (newAmountPaid > 0) {
      originalPayment.status = 'partial';
    }
    
    originalPayment.updatedAt = new Date();
    await originalPayment.save();

    console.log('Payment updated:', {
      paymentId: originalPayment._id,
      newAmountPaid: newAmountPaid,
      status: originalPayment.status
    });

    // Create transaction record with unique transaction ID
    const transaction = new Transaction({
      transactionId: `TXN_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      studentId: submission.studentId,
      paymentId: originalPayment._id,
      submissionId: submission.submissionId,
      amount: submission.amount,
      type: 'payment',
      description: `Payment for ${originalPayment.description}`,
      paymentMethod: submission.paymentMethod,
      receiptFile: submission.receiptFile,
      status: 'completed',
      transactionDate: new Date()
    });

    await transaction.save();

    console.log('Transaction created:', transaction._id);
    console.log('Payment processed successfully for student:', submission.studentId);

  } catch (error) {
    console.error('Error processing approved payment:', error);
    throw error;
  }
}

export default router;